
version: '2'
networks:
  app-tier:
    driver: bridge
services:
  db:
    image: mysql
    networks:
      - app-tier
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zzz
      MYSQL_USER: root
      MYSQL_PASSWORD: zzz
      MYSQL_DATABASE: bug_tracker_development
      ELASTICSEARCH_HOST: elasticsearch
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0' 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
     - db:sql_srv
     - elasticsearch
    depends_on:
      - db
      - elasticsearch
      - rabbit1
    networks:
      - app-tier
  rabbit1:
    image: harbur/rabbitmq-cluster
    hostname: rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-tier
  elasticsearch:
    image: elasticsearch
    networks:
      - app-tier
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      # ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"

volumes:
  elasticsearch: {}