
# version: '2'

# networks:
#   app-tier:
#     driver: bridge
# services:
#   rabbitmq:
#     image: 'bitnami/rabbitmq:latest'
#     ports:
#       - 5672:5672
#     networks:
#       - app-tier
#   app:
#     build: .
#     command: rails server -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/app
#     ports:
#       - "3000:3000"
#     links:
#       - mysql
#     image: 'bugtracker_app_1'
#     networks:
#       - app-tier
#   mysql:
#     image: mysql
#     ports:
#       - "3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: asdasdasd
#       MYSQL_USER: user
#       MYSQL_PASSWORD: asdasdasd
#     networks:
#       - app-tier

version: '2'
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zzz
      MYSQL_USER: root
      MYSQL_PASSWORD: zzz
      MYSQL_DATABASE: bug_tracker_development
      ELASTICSEARCH_HOST: elasticsearch
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0' 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
     - db:sql_srv
     - elasticsearch
    depends_on:
      - db
      - elasticsearch
  rabbitmq:
      image: 'bitnami/rabbitmq:latest'
      ports:
      - 15672:15672
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"

volumes:
  elasticsearch: {}